### ISSUE TITLE
Picard Post Alignment QC / GTF to Ribosomal Interval List: value of $chrom_sizes?

### ISSUE THREAD

**Issue by lijiang825** [HumanCellAtlas/skylab#106]
Hi, 

This is Li Jiang From Peter Kharchenko Lab, Harvard Medical School. I am trying to replicate the whole ss2 pipeline on the cluster-o2 of HMS. I ran into a problem generating ribosomal interval list from gtf. In the script provided, the first line is "samtools view -H $aligned_bam > $chrom_sizes", but the value of $chrom_sizes is not clear to me. Would anyone please clarify this or add some codes/comments to the original codes?

Many thanks,
Li Jiang

**Comment by jishuxu** [comment]
$chrom_sizes is a text file include sam/bam header "@SQ".  I also updated wiki and hope it is clear now.
