### ISSUE TITLE
Examine Optimus STAR parameters

### ISSUE THREAD

**Issue by ambrosejcarr** [HumanCellAtlas/skylab#108]
We're going to adjust the STAR parameters to match CellRanger for the MVP, but careful examination of the parameters is warranted. 

We will be excluding, for example: 
`--outSamPrimaryFlag AllBestScore` (this will cause a single alignment to be output when multiple alignments are primary, yielding imprecise information).

**Comment by kbergin** [comment]
Merging this into a backlog ticket.
