### ISSUE TITLE
CellSortBam and GeneSortBam do not behave _quite_ as intended

### ISSUE THREAD

**Issue by mbabadi** [HumanCellAtlas/skylab#117]
According to the docs in `TagSortBam.wdl`, it is _expected_ that the task `CellSortBam` sorts the records hierarchically: cell barcode > molecule barcode > gene name.  The `samtools` command in the WDL,
```
samtools sort -t GE -t UB -t CB -o cell-sorted.bam "${bam_input}"
```
does not behave as expected; while the output BAM (`cell-sorted.bam`) is sorted by `CB`, `UB` and `GE` are ignored and genomic coordinate is used as the secondary index. A similar issue exists in `GeneSortBam` task.

This causes major issues in certain methods in `sctools`. Since the input files and assumptions are not stringently checked and assumed to be true (e.g. see `sctools:count.py:from_bam`), no exception is thrown, and a wrong result is provided.

**How to reproduce:**
The following three commands produce bit identical outputs:
`samtools sort -t GE -it UB -t CB -o out.bam in.bam`
`samtools sort -t UB -it GE -t CB -o out.bam in.bam`
`samtools sort -t CB -o out.bam in.bam`
i.e. only the last `-t ...` is used.

AI:
-- find an alternative solution for hierarchical sorting of BAM files (Picard?)
-- fix `CellSortBam`
-- fix `GeneSortBam`

**Comment by mbabadi** [comment]
Update: Yossi Farjoun is working on a PR that enables `Picard` to perform arbitrary hierarchical sorting (a new CLI must be written, though).

**Comment by ambrosejcarr** [comment]
Nice, that's really great. Thanks for making that suggestion 👍 

Might the internal model that Yossi writes be useful for further picard-based single-cell tools?

**Comment by mbabadi** [comment]
@ambrosejcarr in short, yes!
