### ISSUE TITLE
Typo in RunBenchmarkingAnalysis.wdl?

### ISSUE THREAD

**Issue by jlchang** [HumanCellAtlas/skylab#122]
Trying to upload RunBenchmarkingAnalysis.wdl into FireCloud and got the following error message:

Error: Invalid WDL: ERROR: Unexpected symbol (line 23, col 17) when parsing 'map'. Expected lbrace, got :. parameter_meta: { ^ $map = :lbrace $_gen8 :rbrace -> $1

It looks like there is an extra colon in line 23 after "parameter_meta"
  parameter_meta: {

Removing the colon resolves the error above (an additional error occurs but is likely due to the version of Cromwell in production FireCloud being a little behind the latest in FireCloud features).

**Comment by kbergin** [comment]
Thank you for submitting, Jean! We'll make sure this gets resolved.
