### ISSUE TITLE
auto-generate dependencies.json for test workflows

### ISSUE THREAD

**Issue by mlin** [HumanCellAtlas/skylab#203]
Recording discussion with @mckinsel 

The test workflows need a tediously prepared [dependencies.json](https://github.com/HumanCellAtlas/skylab/blob/master/test/optimus/scientific/dependencies.json) listing all the imported WDL files, consumed in [run_portability_test.py](https://github.com/HumanCellAtlas/skylab/blob/bfd9051abdfd5aca7a6e92248d1b55ccfb737f52/test/run_portability_test.py#L67). miniwdl's WDL library should make it relatively straightforward to programmatically detect/generate this list given the top-level test workflow and a "PATH" of two directories.

**Comment by kbergin** [comment]
Thanks, Mike. I have filed this in our team backlog so we hopefully get to it someday :) The portability tests have been failing for a while, we need to revisit them.

**Comment by mlin** [comment]
@rhpvorderman has relevant wip -- https://github.com/biowdl/wdl-packager

also discussed on https://github.com/chanzuckerberg/miniwdl/issues/292
