### ISSUE TITLE
max_retries v maxRetries

### ISSUE THREAD

**Issue by mlin** [HumanCellAtlas/skylab#225]
Cromwell's [supported runtime attribute](https://github.com/broadinstitute/cromwell/blob/0f1f434163d8b2c12094b764fc33d6287a593cf4/wom/src/main/scala/wom/RuntimeAttributes.scala#L7) is `maxRetries`; the following specifications of `max_retries` appear to be in error:

1. https://github.com/HumanCellAtlas/skylab/blob/cd4b8ee76d49c4caf384cf04fd816e34521f0732/library/tasks/RSEM.wdl#L54
2. https://github.com/HumanCellAtlas/skylab/blob/29946a3a71f80d250d35e9ab8711d06ca18894b0/pipelines/cellranger/cellranger.wdl#L120

**Comment by kbergin** [comment]
Thank you @mlin I will note this in our backlog. I believe we saw this issue and fixed it in Optimus, but must have missed the others.

**Comment by pshapiro4broad** [comment]
This has been fixed.
