### ISSUE TITLE
--tags in SplitBamByCellBarcode.wdl

### ISSUE THREAD

**Issue by MikeHala** [HumanCellAtlas/skylab#227]
Hello,

I am trying to run the Optimus pipeline with the example_test_inputs.json and I am getting the following error "SplitBam: error: the following arguments are required: -t/--tag".

I have changed line 37 in SplitBamByCellBarcode.wdl from --tags CB CR \ to --tag CB CR \ ,
but now I am getting "SplitBam: error: unrecognized arguments: CR".

Should CB and CR be comma separated? Or just use the CB tag only?

Using: cromwell-43, optimus_v2.0.0 and python 3.5.2.

Thanks,
Mike

**Comment by MikeHala** [comment]
Issue resolved by upgrading to python 3.7.3 and the installing the latest version of sctools from github.

Best,
Mike

**Comment by kbergin** [comment]
Hi Mike, apologies for the delay in response. I'm glad you were able to resolve the issue with the upgrades. Please let us know if you have any feedback on the Optimus pipeline! 

Best,
Kylee
