### ISSUE TITLE
Remediate High Jinja2 vulnerability

### ISSUE THREAD

**Issue by Lilalamar** [HumanCellAtlas/skylab#256]
GitHub reports the following **High** severity vulnerability in HumanCellAtlas/skylab. Please remediate by the end of Q3 Milestone 3.

### Description
Jinja2

### Suggested Remediation
Upgrade Jinja2 to version 2.10.1 or later.

### Details
In Pallets Jinja before 2.10.1, str.format_map allows a sandbox escape. (2) In Pallets Jinja before 2.8.1, str.format allows a sandbox escape.

**Comment by Lilalamar** [comment]
Note: this milestone has not been assigned to this ticket because it doesn't exist in this repo.

**Comment by kbergin** [comment]
Issue moved to [HumanCellAtlas/secondary-analysis #798](https://github.com/HumanCellAtlas/secondary-analysis/issues/798) via [**ZenHub**](https://www.zenhub.com/)
