### ISSUE TITLE
Remediate High urllib3 vulnerability

### ISSUE THREAD

**Issue by Lilalamar** [HumanCellAtlas/skylab#257]
GitHub reports the following **High** severity vulnerability in HumanCellAtlas/skylab. Please remediate by the end of Q3 Milestone 3.

### Description
urllib3

### Suggested Remediation
Upgrade urllib3 to version 1.24.2 or later.

### Details
The urllib3 library before 1.24.2 for Python mishandles certain cases where the desired set of CA certificates is different from the OS store of CA certificates, which results in SSL connections succeeding in situations where a verification failure is the correct outcome. This is related to use of the ssl_context, ca_certs, or ca_certs_dir argument. (2) urllib3 before version 1.23 does not remove the Authorization HTTP header when following a cross-origin redirect (i.e., a redirect that differs in host, port, or scheme). This can allow for credentials in the Authorization header to be exposed to unintended hosts or transmitted in cleartext.

**Comment by Lilalamar** [comment]
Note: this milestone has not been assigned to this ticket because it doesn't exist in this repo.

**Comment by kbergin** [comment]
Issue moved to [HumanCellAtlas/secondary-analysis #799](https://github.com/HumanCellAtlas/secondary-analysis/issues/799) via [**ZenHub**](https://www.zenhub.com/)
