### ISSUE TITLE
Can not find make_grch38_snp_tran_gencode.sh script?

### ISSUE THREAD

**Issue by tianxiahuihui** [HumanCellAtlas/skylab#275]
Hello, I want to use make_grch38_snp_tran_gencode.sh ${gtf_version} ${dbsnp_version} , but I donot find the script. and could you also give the location of ${dbsnp_version} in hg19?

Thank you

**Comment by kbergin** [comment]
@barkasn do you know which script this is?

@tianxiahuihui apologies, we haven't used hg19 for our pipelines, so we may not have that available.
