### ISSUE TITLE
Streamlining the implementation, updating, and (re-)running of pipelines in multiple centers

### ISSUE THREAD

**Issue by LisaSikkema** [HumanCellAtlas/skylab#279]
Dear HCA developers team,

I'm part of the Lung HCA team in the lab of Fabian Theis, and we are trying to think of the best way to synchronize, implement, run and re-run a fastq-->count matrix pipeline in all the computatonial labs involved in the EU-part of the lung-HCA. Please let me know if this is not the right platform to ask the question below ;)

We are dealing with the following:
- sharing of fastqs is not possible due to data protection legislation, but sharing of count matrices is okay
- all data (i.e. from different institutes/centers) should be processed in the same manner before analyzing the aggregated
- the processing pipeline (fastqs --> count matrices) might have to be run and re-run many times on the same data, given new questions/methods/improved pipelines

Ideally it would be possible for one person to re-run the preprocessing pipeline on all the data, whenever needed, working from one location. For example by having limited access to the data from other institutes, if possible (e.g. the ability to run scrips on remote servers, without the ability to view the fastqs?).  In that way, we wouldn't have to contact individual bioinformaticians from each lab individually for every re-run.

Have you guys dealt with similar/the same issues, and if so: do you have any advice on how to approach this? I.e. how to efficiently implement pipeline synchronization/installation, frequent pipeline execution on different servers with limited access to data, etc. 

Any help would be greatly appreciated :) 

Thanks,
Lisa Sikkema

**Comment by kbergin** [comment]
Hi Lisa,

Apologies for not seeing this sooner. I'll follow up with some folks locally to see if anyone has ideas. Leveraging cloud computing and shared pipeline and execution code may help with synchronizing across institutes, should it be difficult to limit access and still reprocess all from one center.

Kylee

**Comment by kbergin** [comment]
This issue has been migrated to our new repository. Apologies that we have not had an answer to it thus far, I'd be curious to hear if you've found any solutions on the new issue

**Comment by LisaSikkema** [comment]
Hi! No problem. In the end we decided to build an easy to install conda-environment/cell ranger pipeline (fastq --> count matrix) that every institute would have to install and run themselves on their own data. Until that is done, we will work with the count matrices as they are provided to us by the data sharers, i.e. with count matrices that are the result of differing pipelines.

**Comment by kbergin** [comment]
Thanks for sharing, Lisa! How are you finding analyzing across count matrices made with different pipelines? I think dealing with that sort of batch effect is something we have always hesitated to do when creating data for our customers, we always reprocess with the same standardized pipeline to guarantee there won't be batch effects created by our pipeline. However, reprocessing is becoming increasingly more expensive as we generate more and more data over time, so we're starting to think about how to balance when to reprocess and when to allow differences in the data. What level of difference is acceptable? The ultimate question :)
