### ISSUE TITLE
Refactor cost script to take server + authentication as parameters

### ISSUE THREAD

**Issue by ambrosejcarr** [HumanCellAtlas/skylab#28]
`skylab/smartseq2_single_sample/run_multi_samples/scripts/calculate_cost_workflow.py` currently hardcodes the server name, username, and password. 

Failing for me (running my own `cromwell 29` server) with the following traceback: 

```
Traceback (most recent call last):
  File "/Users/carra1/projects/skylab/smartseq2_single_sample/run_multi_samples/scripts/calculate_cost_workflow.py", line 248, in <module>
    main()
  File "/Users/carra1/projects/skylab/smartseq2_single_sample/run_multi_samples/scripts/calculate_cost_workflow.py", line 246, in main
    parse_metadata_json(args.input_json_file)
  File "/Users/carra1/projects/skylab/smartseq2_single_sample/run_multi_samples/scripts/calculate_cost_workflow.py", line 215, in parse_metadata_json
    username = meta['username']
KeyError: 'username'
```

**Comment by jishuxu** [comment]
Just want to clarify that the input of this script is a json file which list of subworkflow name, server name and usename, password. it is not hardcoded in this script.

**Comment by ambrosejcarr** [comment]
You're right, sorry; I was imprecise. It does hardcode the server name, though. I was trying to use this on a cromwell other than ours. I'll see if I can adjust it.

**Comment by ambrosejcarr** [comment]
I think I had a misunderstanding about this script: it is specifically designed to capture a subworkflow's cost in absence of the parent workflow, is that correct? 

If one wanted to, for example, run this on SS2, one would run this script once per subworkflow, is that right?

**Comment by kbergin** [comment]
Working on porting tickets to zenhub, so seeing old issues. Is this still relevant?

**Comment by ambrosejcarr** [comment]
Per offline conversations, this script is specific to SS2 cost analysis. I think we can close it.
