### ISSUE TITLE
Can't access /usr/picard/picard.jar when using singularity

### ISSUE THREAD

**Issue by evan-wehi** [HumanCellAtlas/skylab#286]
Optimus.wdl fails with the following error:
```
[First 300 bytes]:Error: Unable to access jarfile /usr/picard/picard.jar
```
when running this task: https://github.com/HumanCellAtlas/skylab/blob/master/library/tasks/FastqToUBam.wdl

The reason seems to be that, in the docker image, the file is only readable by root:
```
$ ls -l /usr/picard/picard.jar 
-rw------- 1 root root 11815043 Aug 17  2017 /usr/picard/picard.jar
```

Because I'm running in a multitenanted HPC environment, I'm using singularity and so I run as a regular user and can't access this file.

It is possible to fix the image so that this file is readable by all users?

**Comment by kbergin** [comment]
I have transferred this issue to our new repository (in progress of being set up). We've heard this issue again recently, and have filed a ticket in our backlog to address.

Thanks
