### ISSUE TITLE
reduce memory requirement

### ISSUE THREAD

**Issue by YOU-k** [HumanCellAtlas/skylab#298]
Hi, I would like to use optimus workflow for 10x v2 data locally. Each of my fastq R1/2 files are about 20GB. If I run optimus.wdl, even if I allocate 300GB, the pipeline would be killed at the call-StarAlign this step. Is there any suggestion to reduce the memory requirement?
Thanks!

**Comment by kbergin** [comment]
Hi @YOU-k apologies for not getting back to you sooner. STAR aligner notoriously uses a large amount of memory. In benchmarking aligners on other data types we have found that hisat2 is a bit more lightweight and performs very similarly to STAR. We haven't tried the aligner on this data type, so we can't speak to whether the same holds true. But you could try subbing it out. Others in the field favor Kallisto, which does pseudoalignment and is much faster and cheaper, I assume it also uses less memory. I am not aware of a way to lower the memory requirements for STAR outright.

Best,
Kylee
