### ISSUE TITLE
emptyDropsWrapper.R bug

### ISSUE THREAD

**Issue by edenisen** [HumanCellAtlas/skylab#302]
Hi,

Looks like there is a bug in R script. Line 125, `ed_param_lower <- opt$verbose` where should be I suppose `ed_param_lower <- opt$ed_lower`

As a result, `emptyDrops` function seems to be running with `lower=1` instead of `lower=100` which changes the results dramatically, at least in samples I checked.

**Comment by kbergin** [comment]
Hi @edenisen -

Thank you so much for spotting and hunting down this bug! We have a pr open #304 and will cut a new release as soon as we can!

**Comment by barkasn** [comment]
This has been fixed in the current master version and will be available in the next Optimus release.
